# Use root/example as user/password credentials

services:
  db:
    image: postgres.custom
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - .sqlfiles:/docker-entrypoint-initdb.d
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  
  api:
    image: python-api
    build: 
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - ./postgres-test.py:/server/postgres-test.py
    restart: always
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    command: uvicorn postgres-test:app --proxy-headers --host 0.0.0.0 --port 8000