name: Security Scan

on:
  workflow_run:
    [cite_start]workflows: ["Build and Test Python"] # Doit correspondre exactement au 'name' du fichier 1 
    types: [completed]

jobs:
  trivy-security:
  
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan Postgres Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'postgres:alpine'
          format: 'table'
          severity: 'CRITICAL'
          [cite_start]exit-code: '1'

      - name: Scan Redis Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'redis:alpine'
          format: 'table'
          severity: 'CRITICAL'
          exit-code: '1'

      - name: Scan Nginx Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nginx:alpine'
          format: 'table'
          severity: 'CRITICAL'
          exit-code: '1'